spring:
  application:
    name: telisa-web-management
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: hyh
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.telisa: debug
    org.springframework.jdbc.support.JdbcTransactionManager: debug

